### ISSUE TITLE
No value assigned to Legendary Dragon Weapon Skins

### ISSUE THREAD

**Issue by bgechachi** [gw2efficiency/issues#1654] opened 2023-01-09 22:26 UTC
Hi,

I was looking through some of the wardrobe skins when I realized the Zhaitan Legendary weapon skin I made was assigned a "no value" in the wardrobe list.

While these items have no value as something that can be sold, I think they should be considered as an increase to account value.  I suppose all the skins would be valued the same.  Some items, such as karma and research notes might be tough to quantify the value of, but certain static items could be added to the value.

One would need the initial 10 Chunk of Ancient Ambergris and 75 Gold, The 100 spirit shards and 350,000 karma are also needed.

Then you have the later part of the collection requiring the Uncharged Fragment that cost a static 200 Jade Runestones, 250 Memory of Aurene and 5 Magic Clover.

So any chance we could get the value of those items added to the skin value on the site?  Thank You!

**Comment by queicherius** [comment] 2023-01-10 07:42
Will be solved by / duplicate of #1605

**Closed by queicherius** 2023-01-10 07:42 UTC
