### ISSUE TITLE
Store hidden dailies and daily history server side

### ISSUE THREAD

**Issue by JoeMylinn** [gw2efficiency/issues#808] opened 2017-08-25 01:27 UTC
Just an idea, to store adjustments made to the daily site as well as the history of how much dailies where done server side instead of client side, so it is possible to sync that between different browsers when using multiple with the same account. Not sure if this is possible with the current account system.

**Comment by queicherius** [comment] 2017-08-25 06:48
This is planned, but atm not really a priority. In the end I want to store filters etc. server side too if you are logged in. (Kinda duplicate of #47, I'll edit that one)

**Closed by queicherius** 2017-08-25 06:48 UTC
