### ISSUE TITLE
Amalgamated gemstones do not show all possible mystic forge recipes

### ISSUE THREAD

**Issue by jacob-keller** [gw2efficiency/issues#270] opened 2016-10-13 05:33 UTC
When attempting to determine optimum cost of amalgamated gemstones the crafting calculator sticks with only one recipe and vastly overprices the actual cost to make them.

**Comment by queicherius** [comment] 2016-10-13 20:57
This is a duplicate of #18.

**Closed by queicherius** 2016-10-13 20:57 UTC
