### ISSUE TITLE
crafted Gift of Dedication does not show up as crafted for Legendary Armor

### ISSUE THREAD

**Issue by CPai1993** [gw2efficiency/issues#752] opened 2017-06-03 18:38 UTC
Gift of Dedication, when crafted, does not show up on the list as crafted when using your own materials on GW2Efficiency.

**Comment by queicherius** [comment] 2017-06-10 19:36
I can't reproduce that, could you post your API key, either here on via admin@gw2efficiency.com?

**Comment by queicherius** [comment] 2017-07-18 20:35
Closing this since there was no feedback in a reasonable timeframe, so I assume the issue fixed itself. 😄

**Closed by queicherius** 2017-07-18 20:35 UTC
Labels: bug, stalled: discussion needed
