### ISSUE TITLE
Daily recap

### ISSUE THREAD

**Issue by bic-mag** [gw2efficiency/issues#807] opened 2017-08-24 22:42 UTC
A page that shows the difference between my current Account State and the State at the last daily reset.

Example: 
At reset I have 120g 400 wood and 25 ore.

I go about my routines doing fracs WvW crafting a bit and open world, and at the end I run an Orr-Gathering Tour

at 11pm I have 123g 250 wood and 230 ore
The Page would show 3g, 205 ore gained, 150 wood spent

This would make it easier to track if my activiies are a net gain or a net loss, and would help to sort out activities, that don't earn a profit in some way.

**Comment by queicherius** [comment] 2017-08-25 06:46
Yes, this is planned. Duplicate of #620

**Closed by queicherius** 2017-08-25 06:46 UTC

**Comment by bic-mag** [comment] 2017-08-25 07:04
Ok cool.
I wasn't sure how in depth you wanted to make it so I limited it to one day. :)
