### ISSUE TITLE
Feature request: multiple user achievements view.

### ISSUE THREAD

**Issue by Mystikite** [gw2efficiency/issues#1048] opened 2018-09-22 16:18 UTC
Given a number of API keys, generate a table showing Achievments and their progress for each user.

**Comment by queicherius** [comment] 2018-09-23 20:51
I am not planning to add enhanced functions for multiple accounts in the near future, since it's only a small portion of the playerbase actively using more than two accounts, and it's a lot of time investment.

---

Duplicate of #101

**Closed by queicherius** 2018-09-23 20:51 UTC
