### ISSUE TITLE
Wrong amount of Meteorite Ingots needed for recipes

### ISSUE THREAD

**Issue by rockafellah1** [gw2efficiency/issues#1298] opened 2020-04-20 08:45 UTC
The crafting calculator lists that you need 50 Meteorite ingots to craft Astralaria III: The Mechanism but you only need 25. The faulty recipes are:

- Cosmic Mechanism: Lists 25 Needed, but only needs 10
- Rune Enchanted RIngs: Lists 25 Needed, but only needs 15

As a very minor thing, the calc also says you need 2 Technomancy Blueprints but you can only get one and only need one. This has virtually no impact but is still wrong.

**Comment by queicherius** [comment] 2020-04-20 18:41
Duplicate of https://github.com/gw2efficiency/issues/issues/166

**Closed by queicherius** 2020-04-20 18:41 UTC
