### ISSUE TITLE
Use buy price instead of sell price in recipe overview (or add it as an option)

### ISSUE THREAD

**Issue by Atemu** [gw2efficiency/issues#1028] opened 2018-08-26 13:08 UTC
You'd make a net loss with almost all non legendary recipes on the first page of the recipe overview when selling at buy prices.  ([Item \#2 in the list currenly](https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-81638), >2000G loss)

The problem is that sell prices of said recipes are sometimes >100x the buy price because you can list your worthless stuff for an arbitrarily high sell price.   
Nobody would buy at those prices of course, so most of them are useless for actually making a profit.

**Comment by queicherius** [comment] 2018-09-11 19:48
Duplicate of #157

**Closed by queicherius** 2018-09-11 19:48 UTC
Labels: A: Crafting, Duration S, Feature, Priority B
