### ISSUE TITLE
Adding Account Cleanup Feature

### ISSUE THREAD

**Issue by maxOS1104** [gw2efficiency/issues#306] opened 2016-11-24 20:17 UTC
Add a "Cleanup" feature to the account tab, like on [GW2Timer](http://gw2timer.com/?page=Account&section=Cleanup), searching to inventory and showcasing item types, helping to cleanup inventory.

**Comment by queicherius** [comment] 2016-11-24 20:42
Duplicate of #90

**Closed by queicherius** 2016-11-24 20:42 UTC
