### ISSUE TITLE
Amalgamated Gemstone crafting recipe does not select the cheapest components

### ISSUE THREAD

**Issue by LamboPita** [gw2efficiency/issues#985] opened 2018-06-23 14:41 UTC
The amalgamated gemstone crafting recipe always suggests dubloons which are the most expensive recipe rather than selecting the cheapest components. This suggests that buying from the TP is always cheaper when, in fact, crafting with other component such as coral orbs is cheaper (e.g., 5 ecto, 3 * 25 coral orbs).

**Comment by queicherius** [comment] 2018-06-23 14:42
Duplicate of #18

**Closed by queicherius** 2018-06-23 14:42 UTC
