### ISSUE TITLE
Unlock Statistics page bugs

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#967] opened 2018-05-15 16:24 UTC
- The text in the dropdown lists is dark even in night mode, and thus illegible.

- I can't type anything in the search bar on that page. I tried both in Firefox and Chrome, and I can type in other search boxes on the site. (Btw it used to work before, not sure what changed.)

**Comment by queicherius** [comment] 2018-05-16 13:31
Thanks, I will take a look :)

**Comment by queicherius** [comment] 2018-05-17 11:41
> The text in the dropdown lists is dark even in night mode, and thus illegible.

I could not reproduce this.

> I can't type anything in the search bar on that page. I tried both in Firefox and Chrome, and I can type in other search boxes on the site. (Btw it used to work before, not sure what changed.)

This is now fixed.

**Closed by queicherius** 2018-05-17 11:41 UTC
Labels: A: Stats, Bug, Duration S, Priority A

**Comment by kazerniel** [comment] 2018-05-17 12:02
Just checked the dropdown list, and it only appears that way in Firefox (in Chrome it's white bg with black text even in night mode.)

It looks like this in FF:
![eff1](https://user-images.githubusercontent.com/5689996/40176198-74d808e4-59d2-11e8-9549-4303a399aa18.png)
![eff2](https://user-images.githubusercontent.com/5689996/40176201-7812bd4c-59d2-11e8-8995-6dcd5e613bf2.png)

**Comment by kazerniel** [comment] 2018-05-17 21:37
Huh that's strange, not sure why the difference. I made sure to turn off any extra stylesheets I have in Stylus. I'm using Firefox ESR 52.8.0 (x64) btw, not sure if it's due to that.
