### ISSUE TITLE
Amalgamated gemstone crafting recipe on calculator is not optimal

### ISSUE THREAD

**Issue by jcogilvie** [gw2efficiency/issues#637] opened 2016-12-26 22:02 UTC
Right now, it's telling me the cost for crafting an Amalgamated Gemstone is much higher than it ought to be because it's including silver, copper, and gold doubloons.  Silver are over 1g each.  Really, a more accurate measure would be [price of the cheapest of all gemstone items] * 9 + [price of a t6 dust].  Or for the 10x recipe, it'd be [price of the cheapest of all gemstone items] * 75 + [price of ecto] * 5.

**Comment by queicherius** [comment] 2016-12-26 22:33
This is caused by #18, so I'll close this as a duplicate. :)

**Closed by queicherius** 2016-12-26 22:33 UTC
