### ISSUE TITLE
Mistborn mote and such don't get listed in Farming tracker

### ISSUE THREAD

**Issue by julienmonnard** [gw2efficiency/issues#1547] opened 2022-01-24 21:33 UTC
Hello! 

When I farm Mistborn Motes and Eternal Ice Shard, while having the Farming tracker started, they never show up in the list, at all.

I didn't try the other currencies, so not sure if it's an isolated issue or if they are also affected

**Comment by queicherius** [comment] 2022-01-24 22:51
Duplicate of https://github.com/gw2efficiency/issues/issues/913

**Closed by queicherius** 2022-01-24 22:51 UTC
