### ISSUE TITLE
Daily: Show tooltip explaining crafting profits

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#802] opened 2017-08-20 22:34 UTC
Currently it shows the timegated crafting recipes, but as far as I see those give account-bound items. I have to go to the item's wiki page, and in the calculator open all the crafting recipes it's used in to see which one would bring the most profit. As it is now, it's not even clear which item the profit listed on the Daily page would come from.

If this feature is to help players make money, it would be very helpful if it was visible what the final TP-able item is to craft.

Thanks!

**Comment by Skaldhor** [comment] 2017-10-04 10:26
Don't overload the daily site.
It's about the things you should do daily, which is crafting the account-bound item.

Later (or every day) you can craft as many of the TP-able items as you want. You don't profit from doing it daily. You could just craft 7 deldrimor every sunday or something like that.

**Comment by kazerniel** [comment] 2017-10-04 12:03
Since then I found [GW2CraftGold](http://www.gw2craftgold.com/best-price-for-46745-Spool-of-Thick-Elonian-Cord), so at least the recipe issue is solved via another site. With that, currently it's just the lack of clear communication on the daily page about the profit amount of each item.

**Comment by Skaldhor** [comment] 2017-10-04 12:38
"The issue is just the lack of clear communication on the daily page about what item gives the profit amount displayed for each entry."
The daily page is not there to give you information about how to make the most gold out of your mats.
This page is meant to remind you to craft the things, which you can only craft once a day.
The idea is just to give you a list of time gated things. If you want to see how to make good profit out of you things, use the crafting calculator or the TP.
Going with your logic, behind every fractal, dungeon path and LS3 map daily should be the item you should buy with relics, tokens and unbound magic.
The page would too cluttered then.

**Comment by queicherius** [comment] 2018-02-12 03:51
Now has a tooltip explaining where the profit is coming from. Showing which one is the most profitable is a bit out of scope for that page.

**Closed by queicherius** 2018-02-12 03:51 UTC
Labels: Feature, Priority C, Ready for Release
