### ISSUE TITLE
Treat currencies (other than karma and gold) as items in the recipe calculator

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#1309] opened 2020-05-11 18:08 UTC
Example: [Mist Diamond](https://wiki.guildwars2.com/wiki/Mist_Diamond) costs two currencies and a stack of an item. Other items in the same recipe tree also use both of these currencies. It would be nice to be able to see exactly how many runs of the repeatable byzantium chest I'd need to complete the recipe.

**Comment by queicherius** [comment] 2020-05-12 00:04
Duplicate of #64

**Closed by queicherius** 2020-05-12 00:04 UTC
