### ISSUE TITLE
Incorrect Value: Festive Confetti Infusion (Vitality)

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [gw2efficiency/issues#1335] opened 2020-07-20 00:39 UTC
So the power stat of the infusion has the correct value.
![](https://i.imgur.com/5WZVMJk.png)

Meanwhile the Vitality stat only shows 3,999g value.
![](https://i.imgur.com/QDZCsl7.png)

**Comment by queicherius** [comment] 2020-07-20 03:02
Duplicate of #1334

**Closed by queicherius** 2020-07-20 03:02 UTC
