### ISSUE TITLE
Bug: Added custom daily and all reset

### ISSUE THREAD

**Issue by strongstancer** [gw2efficiency/issues#1480] opened 2021-08-15 22:52 UTC
Just a few minutes ago I wanted to add 4 custom dailies to my existing dailies, around 10 or so. Hitting "save" just left me with a reset custom daily section with no custom dailies at all. Don't know what exactly caused this, only used normal characters plus : and -. Refreshing browser didn't help.

**Comment by queicherius** [comment] 2021-08-16 19:30
Hey there, I am struggling to find a code-path where this error could happen. 🤔 

Is it possible that you saved while logged into a gw2efficiency account and then logged out? The dailies are stored on your account (and not locally) in this case.

**Comment by strongstancer** [comment] 2021-08-17 11:26
No, I was loggin in before and after the change.

**Comment by queicherius** [comment] 2021-08-20 13:39
Hm, I tried to reproduce this quite a few times and could not figure out a way to make it fail saving in a way that deletes all existing dailies. I'm going to close this as a "freak accident" that might have happened because we had some server issues around that time. Please let me know if it happens again.

**Closed by queicherius** 2021-08-20 13:39 UTC
