### ISSUE TITLE
Mystic Clover / Ad Infinitum Recipe order steps are wrong

### ISSUE THREAD

**Issue by InsulinJunkieDe** [gw2efficiency/issues#1636] opened 2022-09-20 10:08 UTC
When looking up how to craft Ad Infinitum the 1st step is to make Mystic Clovers and the 84th step is buy the Philosopher's Stones for this 1st step:  https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-74155. This is also happening when using own material. (See attached screnshot) 
![Ad Infinitum - Crafting - Calculator](https://user-images.githubusercontent.com/25230928/191230558-c25df08e-fe02-4876-a918-4a920405cc20.png)

**Comment by queicherius** [comment] 2022-09-20 22:39
Duplicate of https://github.com/gw2efficiency/issues/issues/1593

**Closed by queicherius** 2022-09-20 22:39 UTC
