### ISSUE TITLE
Inconsistent options on account value pages

### ISSUE THREAD

**Issue by lemming64** [gw2efficiency/issues#889] opened 2018-01-15 11:57 UTC
eg. on dyes you can show the sell price/buy price/value:

![image](https://user-images.githubusercontent.com/31589475/34941317-23c4998c-f9eb-11e7-8aa7-c5a945b1f87b.png)

but on miniatures you don't have these options, and it seems to default to show the sell price by default only:

![image](https://user-images.githubusercontent.com/31589475/34941327-30f61f86-f9eb-11e7-9150-12a83642eff1.png)

**Comment by queicherius** [comment] 2018-01-30 12:55
Oh good call.

Closed as duplicate of #854

**Closed by queicherius** 2018-01-30 12:55 UTC
Labels: Feature, Idea
