### ISSUE TITLE
Gold numbers off by factor of 10k?

### ISSUE THREAD

**Issue by asmaloney** [gw2efficiency/issues#1625] opened 2022-08-30 18:30 UTC
Examples:

![Screen Shot 2022-08-05 at 19 01 03](https://user-images.githubusercontent.com/391371/187515165-e49461b8-6983-4ca9-8e50-34e615a8b886.png)

![Screen Shot 2022-08-30 at 14 28 49](https://user-images.githubusercontent.com/391371/187515167-9cd193a9-f253-450d-8e41-f31e362fbec9.png)

**Comment by queicherius** [comment] 2022-08-30 18:33
This is copper, duplicate of #1593

**Closed by queicherius** 2022-08-30 18:33 UTC
