### ISSUE TITLE
Astralaria Meteorite Ingot wrong value

### ISSUE THREAD

**Issue by axi92** [gw2efficiency/issues#1257] opened 2020-02-10 18:28 UTC
https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-76158

Astralaria needs not as shown 50x [Meteorite Ingot](https://wiki.guildwars2.com/wiki/Meteorite_Ingot)
It only needs 15 for [Rune Enchanted Rings](https://wiki.guildwars2.com/wiki/Rune_Enchanted_Rings) and 10 for [Cosmic Mechanism](https://wiki.guildwars2.com/wiki/Cosmic_Mechanism)

**Comment by queicherius** [comment] 2020-02-10 19:18
Duplicate of #https://github.com/gw2efficiency/issues/issues/166

**Closed by queicherius** 2020-02-10 19:18 UTC
