### ISSUE TITLE
Recipe unlocks?

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#673] opened 2017-02-15 23:42 UTC
Would there be a way to display locked/unlocked recipes kinda similarly to how we can see locked/unlocked dyes and wardrobe skins? (Preferably with sorting and filtering by crafting profession, acquisition method, level.)

**Comment by queicherius** [comment] 2017-02-15 23:47
This in planned since a while, and I want to add it soon. Just have to find some time. 👍 

Duplicate of #100

**Closed by queicherius** 2017-02-15 23:47 UTC
