### ISSUE TITLE
[Idea] Crafting Calculator "recipe unlocked"

### ISSUE THREAD

**Issue by Hurric4ne** [gw2efficiency/issues#1491] opened 2021-08-23 10:51 UTC
Would be cool to see if i can even craft this recipe i'm currently looking at in the Crafting calculator with any of my chars.
My first idea was a checkbox/dropdown like "Own Materials", but there could be an intermediate recipe i'm missing.

Since there's already an Account recipe Tab to check for unlocked recipes, it wouldn't be a completely new feature.
Maybe adding a "recipe" icon between the Item-Icon and the Wiki-Link with a hover "Recipe unlocked with [character name]" or, if no char has it unlocked, a grayed out Icon/ Icon with a red strikethrough.

Quick Mockup:
![recipe_lock](https://user-images.githubusercontent.com/16904540/130435494-453c75d7-40e8-4259-9520-827b8cc2f185.JPG)
![recipe_unlock](https://user-images.githubusercontent.com/16904540/130435495-c348e1b6-a63c-464b-9dfe-fe30ea0ab6cf.JPG)

**Comment by queicherius** [comment] 2021-08-23 12:07
Duplicate of #55

**Closed by queicherius** 2021-08-23 12:07 UTC
