### ISSUE TITLE
Add a page that helps you level your crafting

### ISSUE THREAD

**Issue by dbenoy** [gw2efficiency/issues#233] opened 2016-09-19 20:22 UTC
Probably a huge request, but I wonder if it's possible to present the site with a character, and ask it "What item could I craft now that would give me the lowest ratio of cost to crafting XP."

Or you could take it even further in depth. I could make something now that would be cheap and would give me lots of experience, but it would boost my crafting level and make it so I'm no longer eligible to craft other items, and it may turn out to have been cheaper if I instead chose slightly more expensive items now, and saved the items with the better ratio until later.

It might be a challenging algorithm, but it would be huge. The economy of the game is artificially inflated by people who just grab a scattershot array of stuff, valuable or otherwise they don't know, and squish it into junk nobody wants just to get crafting XP, pumping up the cost even further of things that people might already want for other reasons, and leaving less obvious but better choices to languish with excessively low prices.

Could be a real service to the community if we could just do all the math.

**Comment by queicherius** [comment] 2016-09-19 20:26
This is a duplicate of #48, but since this is better written than mine I'll close mine and leave this one open.

**Comment by dbenoy** [comment] 2016-09-19 20:27
Ah sorry! I tried to search if it was already there, but I didn't find it.

Also, I see that Issue #111 probably depends on this issue being done first.

**Comment by queicherius** [comment] 2016-09-19 21:07
For #111 I'll scrape data from gw2crafts, until this one here is done (because I want it that issue to go into the next release).

**Comment by rikkuness** [comment] 2016-12-24 03:17
I'm going to have a play with working out an algorithm, sounds like my sort of fun!

@queicherius did you already do any work towards this? Just so I don't replicate effort :)

**Comment by queicherius** [comment] 2016-12-24 14:37
@rikkuness Nope! You could probably write a module that layers onto [`recipe-calculation`](https://github.com/gw2efficiency/recipe-calculation).

So in my mind...

- It would be cool to get the "base" cheapest path, without including own materials. That should be pre-calculated on the backend on some schedule, so the client doesn't have to grab all the recipes (crafting prices are already available in the item data in this case)
- Get the cheapest path while including own materials. This would need to grab all recipes and calculate it dynamically, but it would be fine if it took a while.
- The other fun algorithmic stuff @dbenoy mentioned

All in all, feel free to do whatever you feel like - would all be appreciated. 👍

**Comment by rikkuness** [comment] 2016-12-25 11:43
First stab at something, seems to produce half sensible results but needs plenty of work to nail the algorithm and then add efficiencies and modularise it for consumption.

https://github.com/rikkuness/gw2-crawler/blob/master/profession-training.js

Should probably get back to that Christmas thing too instead of doing this 🎅

**Comment by queicherius** [comment] 2016-12-25 20:48
Cool! Already looks pretty good as far as I can see. 👍

Where did you get the values for the experience per recipe and stuff like that from? Imagined that the be harder than it looks in your code!

> plenty of work to nail the algorithm and then add efficiencies and modularise it for consumption.

Ye, a bit more split up and a few good tests and I think this is good to go!

I am not sure how integrated you want to make this when it gets modularised, but all the gw2efficiency internal modules use [linting and testing from this](https://github.com/queicherius/abc-environment). I could also give you a repository in the [gw2efficiency](https://github.com/gw2efficiency) organisation. I would also be cool if you kept it under your namespace. Your choice. 😄

**Comment by rikkuness** [comment] 2017-01-04 10:46
Sorry been away on a brief holiday. 

The values are actually calculated, I don't expect it's 100% accurate because as of yet I'm not taking into account things like critical crafting exp and I need to account for additional exp for crafting exotics. I based the function I used on the formula here: https://wiki.guildwars2.com/wiki/Crafting#Crafting_experience

Happy to stick it in an efficiency repo, I'll try get some time to do all the linting and testing, then it'd be good to do some real world run throughs and level some characters and compare simulated leveling to "real world"

**Comment by queicherius** [comment] 2017-01-04 14:57
> The values are actually calculated, I don't expect it's 100% accurate because as of yet I'm not taking into account things like critical crafting exp and I need to account for additional exp for crafting exotics. I based the function I used on the formula here: https://wiki.guildwars2.com/wiki/Crafting#Crafting_experience

Ah neat, good to know.

> Happy to stick it in an efficiency repo

Sweet, I'll make a repository then. What do you think about how it should be called? `discipline-leveling`?

> I'll try get some time to do all the linting and testing, then it'd be good to do some real world run throughs and level some characters and compare simulated leveling to "real world"

If you need resources to make the leveling happen (aka some gold), let me know and I'm sure we can figure something out. 👍

**Comment by rikkuness** [comment] 2017-01-04 18:01
> What do you think about how it should be called? discipline-leveling?
Sounds good to me!

> If you need resources to make the leveling happen (aka some gold), let me know and I'm sure we can figure something out. 👍
Also sounds good to me 😄 

Also, you got a better way to chat than someone's Github issue? http://steamcommunity.com/id/rikkuness_net

**Comment by queicherius** [comment] 2018-04-29 17:02
I am going to close this issue because

- I don't have the time to work on this since it is enormous
- Nobody ended up taking this on (and even if, I am not sure I'd like to maintain it)
- It does not give that big of a benefit to the community
  - The feature already exists in the form of gw2crafts.net (they take your API key now afaik)
  - The feature is not used frequently, you don't use daily

**Closed by queicherius** 2018-04-29 17:02 UTC
Labels: Feature, Help Wanted, Idea
