### ISSUE TITLE
Feature Request: Guild Hall Items minus what's in stash on selected "next upgrades"

### ISSUE THREAD

**Issue by woutervs** [gw2efficiency/issues#923] opened 2018-02-21 22:39 UTC
To clarify, it would really be nice if there was a way for guild leaders to select what they want as future upgrades and that on those specific upgrades there would be a difference of what still needs to be gathered/put in the guild treasury.

So basically the total cost minus what's in the guild stash taking into account the selected next upgrades.
With maybe a list apart of the total to gather for the next upgrades.

**Comment by queicherius** [comment] 2018-02-22 09:40
The custom option for guild leaders to select things will probably not happen because it's a pretty niche feature for quite a lot of work.

The difference of a selected Upgrade and what's in the treasury is a duplicate of #61

**Closed by queicherius** 2018-02-22 09:40 UTC
