### ISSUE TITLE
Consider owned materials' TP value in crafting

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1056] opened 2018-10-03 17:08 UTC
I'm sure I've seen it suggested before, but I couldn't find it among the issues:

It would be nice if owned items weren't automatically used for crafting, only if they are actually worth it instead of selling them on the trading post, and buying the next crafting step.

I think this most often occurs with basic refined crafting materials. Eg. atm copper ore proportionally sells for almost 1.5 times as much as its ingot.

**Comment by queicherius** [comment] 2018-10-03 22:47
Duplicate of #224

**Closed by queicherius** 2018-10-03 22:47 UTC
