### ISSUE TITLE
Envoy Insignia recipe is missing the 5g price

### ISSUE THREAD

**Issue by Sejsel** [gw2efficiency/issues#1108] opened 2019-02-07 07:55 UTC
Envoy Insignia can be bought for 25 Legendary Insights + 5 gold, however the crafting recipe (according to #1067 added recently) is missing the 5 gold part.

**Comment by queicherius** [comment] 2019-02-07 19:22
Currencies are not supported in the crafting calculator yet. Duplicate of #64

**Closed by queicherius** 2019-02-07 19:22 UTC
