### ISSUE TITLE
Show original crafting price when using own materials

### ISSUE THREAD

**Issue by xvwyh** [gw2efficiency/issues#1600] opened 2022-06-15 10:44 UTC
This is the option that crafting calculator defaults to for me:
![image](https://user-images.githubusercontent.com/43143822/173805291-dba688f7-bb23-46e3-acbd-2b9a6f6d403a.png)
vs manually selecting the TP option:
![image](https://user-images.githubusercontent.com/43143822/173805319-47e2bd63-4226-4e9b-9f23-0481c64b935d.png)

Seems like if you set "Use own materials: Yes" and you already own all the mats - the calculator assumes that the crafting cost of the item will be 0 and defaults to crafting it, even if buying the item from TP will be straight up cheaper, and by a lot. I can see how this can be preferable in some circumstances, e.g. if the player primarily wants to get rid of their owned materials, but it can also create circumstances when the player will unknowingly burn their wealth for no good reason.

I don't know what a generic solution might be. Here, for example, buying from TP is technically cheaper than crafting, but obviously the player would prefer to use their own materials, right?
![image](https://user-images.githubusercontent.com/43143822/173806877-b17716d6-e9d1-4a76-9867-e97a72a07e94.png)

Exposing it as an option would most likely involve having the user define how big of a loss (compared to buying from TP) they would be willing to take in order to use their own mats, which, I imagine, will look too complicated for some users. 

But at the very least you could display the original crafting price (without using own mats) next to 0c in such circumstances, and let users more easily compare the costs without having to fiddle with radiobuttons, e.g.:
![image](https://user-images.githubusercontent.com/43143822/173807829-8c9d2eda-5a5a-4e44-937d-1a66f12e1721.png)
Won't prevent them from shooting themselves in the foot, but will make it a little more clear than there are sometimes better alternatives to shooting themselves in the foot.

**Comment by queicherius** [comment] 2022-06-15 20:32
Duplicate of https://github.com/gw2efficiency/issues/issues/1479, but the idea to show the original crafting price is not bad, maybe I'll add that as a short-term solution

**Comment by queicherius** [comment] 2023-03-22 12:26
After reconsideration, this is not a feature that I am going to add. The reason for that is that it would be confusing to have the extra number (after user tests).

**Closed by queicherius** 2023-03-22 12:26 UTC
