### ISSUE TITLE
Wallet integration on crafting page

### ISSUE THREAD

**Issue by AMessiah** [gw2efficiency/issues#1278] opened 2020-03-03 19:02 UTC
Suggestion is, when a recipe has a material that is bought from a vendor, to check your wallet to see if you are missing some currency. "Cost breakdown" section could also include those other currencies.

e.g. If a recipe uses "Certificate of Honor" it would check if you have the 500 badges of honor needed and, if not, tell you how much you still need to get

Note: This would only apply to "vendor only" materials, as some currencies could be converted to gold otherwise. (e.g. the gifts from dungeons)

**Comment by queicherius** [comment] 2020-03-03 19:12
Duplicate of https://github.com/gw2efficiency/issues/issues/64

**Closed by queicherius** 2020-03-03 19:12 UTC
