### ISSUE TITLE
Crafting, cheapest price for Amalgamated Gemstone

### ISSUE THREAD

**Issue by EchizenKurage** [gw2efficiency/issues#862] opened 2017-12-04 15:42 UTC
The crafting calculator makes amalgamated gemstones only with dubloons, but there are far more recipes for this out there which are cheaper. See [wiki](https://wiki.guildwars2.com/wiki/Amalgamated_Gemstone/Recipes)

**Comment by queicherius** [comment] 2017-12-04 18:40
Duplicate of #18

**Closed by queicherius** 2017-12-04 18:40 UTC
