### ISSUE TITLE
Laurel merchant item values

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#922] opened 2018-02-21 00:55 UTC
It would probably be helpful to add the value of the laurel cost to the gold cost in the case of skins that are sold by Laurel merchants. Currently the Wardrobe page says that eg. the Gas Mask costs 5g/skin, as if laurels were worth nothing. But if we consider that laurels can be [converted](https://gw2efficiency.com/currencies/laurels) to gold instead of spending it on unlockables, it's clear that in practical terms that skin costs 11+g, not 5.

It kinda resembles the idea behind ticket #224, that just because we already own something it doesn't lose its value.

**Comment by queicherius** [comment] 2018-02-22 09:47
The issue with this is that as soon as I start giving one currency a value, I have to give all other currencies values too, else it'd be unfair. Then I run into the issue of "what is something like spirit shared *actually* worth"? Is it the risky big ticket items? Is it the random upgrades? What about karma? Etc. etc.

**Comment by queicherius** [comment] 2018-02-22 09:47
Duplicate of #109 (at least the basic idea)

**Closed by queicherius** 2018-02-22 09:47 UTC
