### ISSUE TITLE
Tradingpost price graphs only show data up to June 27

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1002] opened 2018-07-25 11:28 UTC

**Comment by queicherius** [comment] 2018-07-25 12:16
This is the case because gw2e uses gw2spidy's charts, and that broke for sometime around that time. I've been trying to work on importing and holding history for prices myself, but so far I did not have time to complete that feature. :(

**Comment by queicherius** [comment] 2018-07-25 12:16
Duplicate of #117

**Closed by queicherius** 2018-07-25 12:16 UTC
