### ISSUE TITLE
Add a Catalog tab

### ISSUE THREAD

**Issue by maxOS1104** [gw2efficiency/issues#307] opened 2016-11-24 20:19 UTC
Adding a "Catalog" Tab, similar to [GW2Timers](http://gw2timer.com/?page=Account&section=Catalog) catalog feature, searching through all accounts and listing special items in categories, such as keys or the new currencies.

**Comment by queicherius** [comment] 2016-11-24 20:41
Duplicate of #153

**Closed by queicherius** 2016-11-24 20:41 UTC
