### ISSUE TITLE
Crafting interface not recognizing craftable items

### ISSUE THREAD

**Issue by SeventhSolar** [gw2efficiency/issues#1173] opened 2019-06-02 03:34 UTC
Although crafting calculation for Tooth of Frostfang initially worked normally, at some point today, I refreshed the page and it bugged out.  Many craftable items are now listed as "Not sold or crafted," but not all of them.  See screenshot.

![bugged-crafting](https://user-images.githubusercontent.com/26511899/58756372-ba44b700-84c5-11e9-89d9-6d47682e33c1.png)
![bugged-crafting-more](https://user-images.githubusercontent.com/26511899/58756425-80c07b80-84c6-11e9-9556-5d5d5e6c287c.png)

**Comment by SeventhSolar** [comment] 2019-06-02 03:35
I've been refreshing the page throughout the day, but it hasn't fixed itself yet.  Other item pages don't seem to be experiencing the same problem.  Ctrl+f5 doesn't do anything, nor does closing the tab and manually searching Tooth of Frostfang in a new one.

**Comment by SeventhSolar** [comment] 2019-06-02 03:45
![legendaries](https://user-images.githubusercontent.com/26511899/58756467-2247cd00-84c7-11e9-945f-d521c33332fb.png)
![expertise-in-axe](https://user-images.githubusercontent.com/26511899/58756471-43102280-84c7-11e9-9c61-d3152ab702b2.png)
![axe-blade](https://user-images.githubusercontent.com/26511899/58756477-5fac5a80-84c7-11e9-8e95-792519b65734.png)

**Comment by queicherius** [comment] 2019-06-02 10:54
This was caused by the API temporarily not emitting the recipes. Should be fixed now.

**Closed by queicherius** 2019-06-02 10:54 UTC
