### ISSUE TITLE
Legendary Runes and Sigils missing from account statistics

### ISSUE THREAD

**Issue by zrax** [gw2efficiency/issues#1616] opened 2022-07-29 20:38 UTC
The [account statistics](https://gw2efficiency.com/account/statistics) page has a few categories for Legendary unlocks, including "Any", but apparently legendary Runes and Sigils are not included in any of those counts.

**Comment by queicherius** [comment] 2022-07-29 20:43
Duplicate of https://github.com/gw2efficiency/issues/issues/1555

**Closed by queicherius** 2022-07-29 20:43 UTC
