### ISSUE TITLE
[Minor Issues] Draconis Mons Hero

### ISSUE THREAD

**Issue by Hurric4ne** [gw2efficiency/issues#1539] opened 2021-11-23 12:53 UTC
1. https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-81896
Heavy Houndskin Mantle still shows as "needed" , even though i've already obtained it; The Skin-Collection shows it as collected, aswell as the Achievement "Flashpoint" Mastery".

2. [A Henge Away from Home](https://wiki.guildwars2.com/wiki/The_Wayfarer%27s_Henge) is missing completely. I guess you could check if someone has [The Wayfarer's Henge Skin](https://wiki.guildwars2.com/wiki/The_Wayfarer%27s_Henge_(skin))

**Comment by queicherius** [comment] 2021-11-23 19:21
Duplicate of https://github.com/gw2efficiency/issues/issues/1240

Right now our support of achievement collections is pretty rudimentary in the calculator, it's usually better to use the achievement page: https://gw2efficiency.com/account/achievements?filter.search=Draconis%20Mons%20Master

**Closed by queicherius** 2021-11-23 19:21 UTC
