### ISSUE TITLE
The Olmakhan Bandolier recipes call for crafting the first bag and then repeating the achievement for the upgrades

### ISSUE THREAD

**Issue by Artanis** [gw2efficiency/issues#977] opened 2018-06-11 06:44 UTC
For example: https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-87225

Instead, the crafting recipes learned after earning the first reinforced bag should be used.

**Comment by queicherius** [comment] 2018-07-04 20:59
Duplicate of #983

**Closed by queicherius** 2018-07-04 20:59 UTC
Labels: A: Crafting, Chore, Duration S, Priority C
