### ISSUE TITLE
Add per-item order/instant-buy option to crafting recipe tree

### ISSUE THREAD

**Issue by benjaminhenne** [gw2efficiency/issues#1153] opened 2019-05-03 23:12 UTC
Receiving buy orders for slow-moving items like weapon/armour parts (hafts/soles/...) takes forever, and sometimes the difference between order and instant-buy is reasonably close.

In those cases, switching (only) these items to instant-buy would allow more accurate price and profit calculation.

**Comment by queicherius** [comment] 2019-05-04 17:28
Duplicate of #58

**Closed by queicherius** 2019-05-04 17:28 UTC
