### ISSUE TITLE
[Addition Request] Account Statistics - Emblem of the Avenger

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [gw2efficiency/issues#1303] opened 2020-05-02 22:04 UTC
Currently Emblem of the Avenger is only used to create Conflux the Legendary ring, and you only need 1 of them.  So like how Legendary Spikes you only need a few for both the Back piece, and Slumbering Conflux.  If I figured Emblem of the Avenger will just start piling up, and have no value whatsoever, but it would be interested to see if people hoard these for fun.  Much like they do with Legendary Spikes.

**Comment by queicherius** [comment] 2020-11-08 16:51
Duplicate of #1288

**Closed by queicherius** 2020-11-08 16:51 UTC
Labels: 1-Type: Feature, 2-Priority: B, 3-Complexity: Low, 4-Impact: Low, 5-Area: Statistics, 9-Status: For next release
