### ISSUE TITLE
Factor (enormous) Chests of legendary shards into Gen2 leggy weapon crafting

### ISSUE THREAD

**Issue by Prezombie** [gw2efficiency/issues#1561] opened 2022-02-24 22:05 UTC
Have some chests of legendary shards, pick a gen2 to craft, check the use own materials.

Logically, it should use those chests before crafting more.

Secondly, it's not immediately obvious, but when making a non-offhand weapon, it's cheaper to make 100 offhand weapon shards, craft an enormous chest of legendary shards, and pick the 75 shards you want out of it. Add that as an alternative crafting route for the shards in the calculator?

**Comment by queicherius** [comment] 2022-02-25 21:38
Duplicate of https://github.com/gw2efficiency/issues/issues/1398#issuecomment-769124808 and

**Closed by queicherius** 2022-02-25 21:38 UTC
