### ISSUE TITLE
Blacklist some merchant recipes in crafting calculator

### ISSUE THREAD

**Issue by malagus** [gw2efficiency/issues#1652] opened 2022-12-19 17:37 UTC
Please blacklist some of random new random recipes from merchants. like this
https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-24275
For example, now every item that require  Pile of Luminous Dust has it's value decreased because calculator assume that you can buy any amount  from guild merchant , but it's only radome chance that you can buy one per day if it's actually listed and only if your guild have special upgrade

**Comment by queicherius** [comment] 2022-12-19 17:44
Duplicate of #1593

**Closed by queicherius** 2022-12-19 17:44 UTC
