### ISSUE TITLE
Custom Recipes: Merchants: missing currency costs

### ISSUE THREAD

**Issue by Iiridayn** [gw2efficiency/issues#1543] opened 2021-12-19 05:23 UTC
I've noticed this particularly with the sealed package of snowballs (1 snowflake _plus_ 7000 karma) and swim speed infusions (missing the 448 copper per level per purchase). Neither are trivial costs, and should be listed somehow as part of the "recipe", or at least in a custom field.

I'd guess offhand these come from http://gw2profits.com/json? That API reports currencies as negative item IDs; this is feasible, though I'd prefer another field honestly. Multiple currencies are possible (eg, "Vial of Chak Acid" for 8 Ley Line Crystal + 24 Copper), so perhaps a JSON object, keys are currencys?

**Comment by queicherius** [comment] 2021-12-19 11:58
Duplicate of #64, right now these currencies are not calculated at all, we just show the current merchant prices

**Closed by queicherius** 2021-12-19 11:58 UTC

**Comment by Iiridayn** [comment] 2021-12-23 06:37
Respectfully, this is more of a prerequisite than a duplicate. This can be done without that, but that cannot be done without this.

I'm not asking them to be calculated; just that the current merchant prices shown are correct and not misleading.

**Comment by queicherius** [comment] 2021-12-23 11:46
For me this is the same ticket, because getting a system in place to maintain merchant prices in I way that I dont have to sling manual data around is about 95% of the effort that needs to go into it and only about 5% is for showing it in the frontend and adding them up.
