### ISSUE TITLE
Add Gift of desert variant to legendary crafting.

### ISSUE THREAD

**Issue by Lusaphor** [gw2efficiency/issues#951] opened 2018-04-20 07:41 UTC
Add a way to select which gift for the newer legendaries, gift of Maguuma or Gift of the desert you would like to use, or would be cheaper. It will help with crafting cost, and expectations.

**Comment by queicherius** [comment] 2018-04-21 20:27
This is currently not possible, because only one recipe can exist in our internal system per output item.

Duplicate of #18

**Closed by queicherius** 2018-04-21 20:27 UTC
