### ISSUE TITLE
Kamohoali'i Kotaki missing Jungle Magics: Spear Edition

### ISSUE THREAD

**Issue by maciejstepie** [gw2efficiency/issues#1792] opened 2024-06-20 11:25 UTC
Buying `Jungle Magics: Spear Edition` from LA merchant is missing in steps and by that also missing amount of geodes to craft spear.

![image](https://github.com/gw2efficiency/issues/assets/56389913/045bf5c7-060e-407e-b7da-8c579bd5ea9c)
![image](https://github.com/gw2efficiency/issues/assets/56389913/3509731f-afd9-4f00-adae-6356835add7e)
![image](https://github.com/gw2efficiency/issues/assets/56389913/e6fb6f09-32df-4bda-900b-c37796c59a8f)

**Comment by Aguileitus** [comment] 2024-06-30 04:00
Check https://github.com/gw2efficiency/issues/issues/1781

**Comment by queicherius** [comment] 2024-06-30 07:10
Duplicate of #1781

**Closed as completed by queicherius** 2024-06-30 07:10 UTC
Labels: Data
