### ISSUE TITLE
28 Slot Orichalcum Locker

### ISSUE THREAD

**Issue by mirtisdyleris** [gw2efficiency/issues#845] opened 2017-11-08 00:30 UTC
I want to upgrade my 24 Slot Orichalcum Lockers to 28 Slot ones. The Crafting Calculator isnt taking into consideration that i already have the 24 slot ones. (even if i put in the option that it should take into consideration my mats) even if i take the 24 slot bag out of the inventory slot and put it into the inventory..

pls fix

**Comment by queicherius** [comment] 2017-11-08 04:02
It should work when you take it out of the bag slot, keep in mind that the API can take around 10 minutes to update sometimes. Can you confirm that it's still broken after waiting 10 minutes after removing it from the bag slot?

**Comment by mirtisdyleris** [comment] 2017-11-08 13:20
Yes I tested it now again - still doesnt work. Please also make it that it works when the thing is in the inventory slot.. (it doesnt even work if it is in the normal inventory - tested it now again) Maybe because the item changes after you soulbind it?

**Comment by queicherius** [comment] 2017-12-04 02:12
If it's not picking up in the inventory, it's an API issue. If it's a different recipe it's a duplicate of another issue here, so I'm gonna close this one out.

**Closed by queicherius** 2017-12-04 02:12 UTC
