### ISSUE TITLE
Ability to see character specific earned Hero Points of character screen

### ISSUE THREAD

**Issue by safrant** [gw2efficiency/issues#1295] opened 2020-04-10 22:58 UTC
I would like to see the character-specific hero points on the character summary screen, or at least on the character details screen.  It would make it much easier to figure out which toon needs to go on a hero point run.

**Comment by queicherius** [comment] 2020-04-12 00:32
Duplicate of #733 
Currently not a priority, but will be included once I start the character page rework (whenever that is)

**Closed by queicherius** 2020-04-12 00:32 UTC
