### ISSUE TITLE
Legy gen 2 weapon shards are not counted for crafting

### ISSUE THREAD

**Issue by CuChulla1nn** [gw2efficiency/issues#1727] opened 2023-11-25 21:38 UTC
When calculating costs for crafting [Shards of Endeavor] for gen 2 legendary mace. Shards from the bank are not calculated from the bank. 

Example: Want to craft 60 shards while 9 in the bank. Materials for all 60 are calculated without taking the 9 in the bank into account.

**Comment by queicherius** [comment] 2023-11-25 22:59
They definitely should - did they show up on the [bank page](https://gw2efficiency.com/account/bank)? If no then it's just the API that was delayed, if yes then there's more to it.

**Comment by queicherius** [comment] 2023-11-30 20:16
Hmm, I'm gonna close this because I can't reproduce this, but I'll keep an eye out. 🤔 Feel free to re-open if it happens again.

**Closed by queicherius** 2023-11-30 20:16 UTC
