### ISSUE TITLE
organize / filter ascended armor crafting costs

### ISSUE THREAD

**Issue by FreezyExp** [gw2efficiency/issues#815] opened 2017-09-06 08:49 UTC
A simple light / medium / heavy  filter would be wonderful

as a side note, an additional filter for stuff like: berserker/zojja, minstrel/maklain etc
and if it's not too much to ask for, a quick: cheaper with stat change check box

https://gw2efficiency.com/crafting/ascended

**Comment by queicherius** [comment] 2017-09-08 17:52
This would be solved with the completion of another ticket. Duplicate of #157

**Closed by queicherius** 2017-09-08 17:52 UTC
