### ISSUE TITLE
Feature Request: Add account bound materials and currencies to all crafting 'cost' displays

### ISSUE THREAD

**Issue by dbenoy** [gw2efficiency/issues#234] opened 2016-09-19 21:09 UTC
When I look up crafting recipes, and I see the 'cost' in gold, I was wondering if I could also mouse over or click or something to display all the account-bound costs, like currencies and materials that you can't buy.

**Comment by dbenoy** [comment] 2016-09-19 21:21
It would also be nice if it had a tiny blurb beside each one explaining where to find it.

**Comment by queicherius** [comment] 2016-09-20 11:05
Duplicate of #64

**Closed by queicherius** 2016-09-20 11:05 UTC
