### ISSUE TITLE
Agony Resistance can be wrong on character page

### ISSUE THREAD

**Issue by Algent** [gw2efficiency/issues#847] opened 2017-11-10 12:42 UTC
Hi,
One of my char is missing a +9 from offhand in the total.

Reason is probably because I'm running scepter/nothing nothing/torch for geomancy sigil.
In this case it should count the numbers from the other slot.

![image](https://user-images.githubusercontent.com/847891/32658975-b863f54a-c61c-11e7-98c8-fde294893340.png)

**Comment by queicherius** [comment] 2017-11-10 12:57
Duplicate of #746

**Closed by queicherius** 2017-11-10 12:57 UTC
