### ISSUE TITLE
integrated fractal matrix recipe doesn't show fractal relics

### ISSUE THREAD

**Issue by jacob-keller** [gw2efficiency/issues#970] opened 2018-05-31 03:09 UTC
The recipe for "crafting" (really, buying) integrated fractal matrices does not show the cost of fractal relics. Is this an API limitation? Should it include fractal relics? I know things which cost karma (like obsidian shards) have the karma cost show up in the cost to buy the item.. Shouldn't the integrated fractal matrices be treated the same way?

**Comment by queicherius** [comment] 2018-05-31 14:32
Currently, no currencies at all are shown in the crafting calculator, with the exception of some items that are hardcoded. This is a limitation of the crafting calculator itself.

Duplicate of #64

**Closed by queicherius** 2018-05-31 14:32 UTC
