### ISSUE TITLE
Add Buy Price and Crafting Buy/Sell Profit to Recipe Search

### ISSUE THREAD

**Issue by Kantharr** [gw2efficiency/issues#1177] opened 2019-06-08 23:16 UTC
It would be nice if there was a Buy Price column in the Recipes Search along with a Crafting Buy/Sell Profit columns for displaying the profits between selling the crafted item to the Highest Buyer vs the Lowest Seller. Obviously selling to the Lowest Seller would give more profit but selling to the Highest Buyer would provide immediate small profits for those that desires it.

**Comment by queicherius** [comment] 2020-11-14 19:21
Duplicate of #1208

**Closed by queicherius** 2020-11-14 19:21 UTC
Labels: 1-Type: Feature, 2-Priority: Idea, 3-Complexity: Low, 4-Impact: Low, 5-Area: Crafting
