### ISSUE TITLE
Add savings, profit (buy) and profit (sell) to cost breakdown when crafting multiple recipes

### ISSUE THREAD

**Issue by Xyttra** [gw2efficiency/issues#1797] opened 2024-07-01 06:20 UTC
In the crafting tool, add option to select between "instant sell" and "sell order" when having multiple recipes for the purpose of calculating profit. This option is available when we only have one recipe but not for multiple recipes.

Also, with multiple recipes, we can see total cost but not total profit, that would be handy as well ^^

**Comment by queicherius** [comment] 2024-10-21 16:40
Duplicate of #1702

**Closed as completed by queicherius** 2024-10-21 16:40 UTC
Labels: Feature
