### ISSUE TITLE
Unlock statistics: add value to achievements

### ISSUE THREAD

**Issue by maxOS1104** [gw2efficiency/issues#891] opened 2018-01-20 15:53 UTC
First of all, great feature! Thank you!
But I noticed something: achievements have no value attached to them. 
Maybe you can use that column to show the maximum of achievement points achievable for this achievement?

**Comment by queicherius** [comment] 2018-01-20 16:06
I wanted to show the price of the achievement there (basically the completion cost), since that's more inline with how the other unlocks work. However, this needs some extra backend work.

**Comment by RLHawk1** [comment] 2018-06-22 20:27
Is there any chance you could add Achievement point value also then?  I really like using this screen to show locked achievements sorted by the % unlocked by playerbase to see somewhat low hanging fruit. But it'd be nice to see AP value also.

**Comment by queicherius** [comment] 2018-06-23 14:37
@RLHawk1 I made a [new issue](https://github.com/gw2efficiency/issues/issues/984) out of your request, since that is a lot easier and might get in on it's own.

**Comment by queicherius** [comment] 2018-07-04 20:55
Duplicate of #110

**Closed by queicherius** 2018-07-04 20:55 UTC
Labels: A: Stats, Duration L, Feature, Idea
